name = "riwaaz"
compatibility_date = "2024-12-30"

[vars]
SHEETS_CSV_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRqD3n6XJkzZ-Slx1yl5aDab-7LWV2ZCxqww45rRWKPAh0ISMSvNXYVBvwjthKv1ujMTbm4WXmI2fXG/pub?output=csv"
